### PR TITLE
Added Code to fetch and store Nodes data from OSM and Mock API for vehicles

### PR DESCRIPTION
**Pull request by sitaramshelke**
The current code allows to fetch the data from OSM online or from stored pbf file. Next task is to be able to add ways and relations.

### CODE REVIEW

**Comment by sitaramshelke** [comment]
Fixes #4 

```
{
  "Vehicles": [
    "Fiat Fiorino",
    "Smart Roadster",
    "Sam",
    "Citysax",
    "MUTE",
    "Spyder-S",
    "Think",
    "Luis",
    "STROMOS",
    "Karabag Fiat 500E",
    "Lupower Fiat 500E"
  ]
} 
```

**Comment by fabianbormann** [comment]
@sitaramshelke I think Max will merge your pull-request soon, :blush: but you can help him by increase your code readability:
- Choose clear and readable variable names (eg. `words` or `wordCount` instead of `wc`) 
- Try to use constants and remove magic numbers

``` golang
if nc != 2060543 {
...
}
```

``` golang
// Somewhere at the top
const EXACT_NODE_COUNT =  2060543

...

if nodeCount != EXACT_NODE_COUNT {
...
}
```

"Clean Code" by Robert C. Martin is a really cool book which helps me a lot to improve my coding style. :+1: Sure the book is about java, but I think many of his tips are assignable to any other language.

Cheers,
Fabian

**Comment by sitaramshelke** [comment]
@fabianbormann Thank you for the review and yes I completely agree with you. I will commit the improvements soon. :smiley:

**Comment by sitaramshelke** [comment]
@maxlorenz has already added better formatted code, so if not needed I think this request can be closed now.

**Pull request merged**
